name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: سحب الكود
        uses: actions/checkout@v3

      - name: تسجيل الدخول لـ Docker Hub
        uses: docker/login-action@v3
        with:
          username: zeya10
          password: dckr_pat_E6COZomTL3LJkh5_0zA5WfcrO3c

      - name: بناء صورة Docker
        run: docker build -t zeya10/myimage:latest .

      - name: رفع صورة Docker
        run: docker push zeya10/myimage:latest